management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: StudentApplication
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/userdb
        username: root
    cloud:
        loadbalancer:
            ribbon:
                enabled: true
                eureka:
                    enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect


server:
    port: 8085


eureka:
    instance:
        instance-id: ${spring.application.name}:${random.int}
        lease-expiration-duration-in-seconds: 2
        lease-renewal-interval-in-seconds: 1
    client:
        service-url:
            defaultZone: http://localhost:9091/eureka



