management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/userdb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

server:
    port: 8080

---

server:
    port: 8761

spring:
    application:
        name: StudentApplication

eureka:
    client:
        register-with-eureka=false
        fetch-registry=false
    server:
        enable-self-preservation: false
---
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: true
                eureka:
                    enabled: true
